#!/bin/sh
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

disable_udc="/etc/.disable_udc"
udc_config=/sys/kernel/config/usb_gadget/g1/UDC

function enable_udc(){
    while [ 1 ];do
        udc=`ls /sys/class/udc 2>/dev/null`
        isudc=`cat $udc_config 2>/dev/null`
        if [ "x$isudc" = "x" ] && [ -f $udc_config ]; then
            echo $udc > $udc_config
        fi
        sleep 1
        if [ -f $disable_udc ];then
            rm $disable_udc
            break
        fi
    done
}

function start_adb(){

    serialnumber=$1
    if [ "x$serialnumber" = "x" ];then
        serialnumber="0402101560"
    fi
    printf "Starting mass usb share. "
    mkdir -p /root/share/
    if [ -b /dev/mmcblk0p6 ];then
        mount /dev/mmcblk0p6 /root/share
    fi
    # config ptmx
    mkdir -p /dev/pts
    mount -t devpts none /dev/pts

    # config adb function
    mount -t configfs none /sys/kernel/config
    mkdir -p /sys/kernel/config/usb_gadget/g1
    echo 0x1d6b > /sys/kernel/config/usb_gadget/g1/idVendor
    echo 0x0104  > /sys/kernel/config/usb_gadget/g1/idProduct
    mkdir -p /sys/kernel/config/usb_gadget/g1/strings/0x409
    echo "123456789" > /sys/kernel/config/usb_gadget/g1/strings/0x409/serialnumber
    echo "COMPANY"  > /sys/kernel/config/usb_gadget/g1/strings/0x409/manufacturer
    echo "Mass Storage Gadget 1" > /sys/kernel/config/usb_gadget/g1/strings/0x409/product
    mkdir -p /sys/kernel/config/usb_gadget/g1/configs/c.1
    mkdir /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409
    echo "mass_storage"  > /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409/configuration
    mkdir /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0
    ln -s /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0 /sys/kernel/config/usb_gadget/g1/configs/c.1

    echo /dev/mmcblk0p6  > /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file
    udc_controller=`ls /sys/class/udc`
    echo $udc_controller > /sys/kernel/config/usb_gadget/g1/UDC
    sleep 1
    # enable udc
    UDC_DEVICE=`find -name "usb_device"`
    cat $UDC_DEVICE
    #cat /sys/bus/platform/drivers/otg\ manager/soc@3000000:usbc0@0/usb_device

    enable_udc &
}

case "$1" in
    start|"")
        start_adb $serialnumber
        ;;
    stop)
        printf "Stopping adbd "
        touch $disable_udc
		sleep 2
        killall adbd &
        [ $? -eq 0 ] && echo "OK" || "FAIL"
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

